# FROM openjdk:17-jdk
# LABEL author="Prachi"
# RUN apt update && apt upgrade -y && \
#     wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key && \
#     echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null && \
#     apt-get update && apt-get install -y jenkins
# CMD [ "java","-jar","/usr/share/jenkins/jenkins.war"]
# EXPOSE 8080
FROM openjdk:17-alpine


# Set the author label
LABEL author="Prachi"

# Install necessary packages including Jenkins
RUN apt update && apt upgrade -y && \
    wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key && \
    echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null && \
    apt-get update && apt-get install -y jenkins

# Expose Jenkins port
EXPOSE 8080

# Start Jenkins
CMD ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
